/**
 * Strudel player type definitions for the Strudel Agent UI
 *
 * Types for interacting with the @strudel/web library.
 * Based on actual @strudel/web API from unpkg.com/@strudel/web@latest/web.mjs
 *
 * Official API:
 * - initStrudel(options?) -> Promise<Repl>
 * - evaluate(code, autoplay=true) -> Promise<pattern>
 * - hush() -> void (stops all patterns)
 * - Pattern.prototype.play() -> plays a single pattern
 */

/**
 * Player state values
 */
export type PlayerState = 'stopped' | 'playing' | 'paused' | 'loading' | 'error';

/**
 * Strudel pattern - represents a compilable Strudel code string
 */
export interface StrudelPattern {
	/** Unique identifier for this pattern */
	id: string;

	/** The Strudel code */
	code: string;

	/** Optional name for the pattern */
	name?: string;

	/** Whether this pattern is currently active in the player */
	isActive?: boolean;
}

/**
 * Global player state
 * Manages playback state for the Strudel REPL
 */
export interface GlobalPlayerState {
	/** Whether Strudel audio engine is initialized */
	initialized: boolean;

	/** Current player state */
	state: PlayerState;

	/** Current volume (0-1) */
	volume: number;

	/** Current tempo (cycles per second) */
	cps: number;

	/** IDs of clips currently loaded in the player */
	loadedClips: string[];

	/** Combined pattern code (generated by stack()) */
	combinedPattern?: string;

	/** Optional error message if state is 'error' */
	error?: string;
}

/**
 * Strudel evaluation result
 */
export interface EvaluationResult {
	/** Whether evaluation was successful */
	success: boolean;

	/** Error message if evaluation failed */
	error?: string;

	/** Error line number if applicable */
	errorLine?: number;

	/** Compiled pattern if successful */
	pattern?: unknown;
}

/**
 * Helper to create a default player state
 */
export function createDefaultPlayerState(): GlobalPlayerState {
	return {
		initialized: false,
		state: 'stopped',
		volume: 0.7,
		cps: 0.5,
		loadedClips: []
	};
}

/**
 * Helper to check if player is active (playing or paused)
 */
export function isPlayerActive(state: PlayerState): boolean {
	return state === 'playing' || state === 'paused';
}

/**
 * Helper to check if player can be started
 */
export function canStartPlayer(state: PlayerState): boolean {
	return state === 'stopped' || state === 'paused';
}

/**
 * Helper to check if player can be stopped
 */
export function canStopPlayer(state: PlayerState): boolean {
	return state === 'playing' || state === 'paused';
}

/**
 * Extend the Window interface to include Strudel globals
 * These are exposed by @strudel/web when loaded via CDN
 */
declare global {
	interface Window {
		/** Initialize Strudel REPL - must be called once before evaluate/hush */
		initStrudel?: (options?: { autostart?: boolean }) => Promise<unknown>;

		/** Evaluate Strudel code and optionally autoplay */
		evaluate?: (code: string, autoplay?: boolean) => Promise<unknown>;

		/** Stop all patterns immediately */
		hush?: () => void;
	}
}
